using Manifolds, ManifoldsBase, Manopt, Test

@testset "Manopt.jl" begin
    @test Manopt.Rn_default() === :Manifolds
    @testset "Base Interface tests" begin
        include("base/test_callbacks.jl")
    end
    @testset "Commons" begin
        include("commons/test_counts.jl")
        include("commons/test_constrained_sets.jl")
        include("commons/test_debug.jl")
        include("commons/test_defaults_factory.jl")
        include("commons/test_difference_of_convex_objectives.jl")
        include("commons/test_embedded_objective.jl")
        include("commons/test_functions.jl")
        include("commons/test_constrained_objective.jl")
        include("commons/test_cache_objective.jl")
        include("commons/test_conjugate_gradient_coefficients.jl")
        include("commons/test_gradient_objective.jl")
        include("commons/test_hessian_functions.jl")
        include("commons/test_higher_order_primal_dual_objectives.jl")
        include("commons/test_interior_point_newton_objectives.jl")
        include("commons/test_keywords.jl")
        include("commons/test_mesh_adaptive_ingredients.jl")
        include("commons/test_nelder_mead_ingredients.jl")
        include("commons/test_nonlinear_least_squares_objective.jl")
        include("commons/test_objectives.jl")
        include("commons/test_parameters.jl")
        include("commons/test_primal_dual_objectives.jl")
        include("commons/test_problems.jl")
        include("commons/test_proximal_objectives.jl")
        include("commons/test_repl.jl")
        include("commons/test_record.jl")
        include("commons/test_robustifiers.jl")
        include("commons/test_scaled_objective.jl")
        include("commons/test_states.jl")
        include("commons/test_stepsizes.jl")
        include("commons/test_stochastic_gradient_objective.jl")
        include("commons/test_stopping_criteria.jl")
        include("commons/test_storage_actions.jl")
        include("commons/test_subgradient_objective.jl")
        include("commons/test_symmetric_linear_systems.jl")
        include("commons/test_vectorial_function.jl")
    end
    @testset "Helper Tests        " begin
        include("helpers/test_checks.jl")
        include("helpers/test_linesearches.jl")
        include("helpers/test_manifold_extra_functions.jl")
    end
    @testset "Solver Tests        " begin
        include("solvers/test_adaptive_regularization_with_cubics.jl")
        include("solvers/test_alternating_gradient.jl")
        include("solvers/test_augmented_lagrangian.jl")
        include("solvers/test_cma_es.jl")
        include("solvers/test_convex_bundle_method.jl")
        include("solvers/test_ChambollePock.jl")
        include("solvers/test_conjugate_gradient.jl")
        include("solvers/test_difference_of_convex.jl")
        include("solvers/test_Douglas_Rachford.jl")
        include("solvers/test_conjugate_residual.jl")
        include("solvers/test_cyclic_proximal_point.jl")
        include("solvers/test_exact_penalty.jl")
        include("solvers/test_Frank_Wolfe.jl")
        include("solvers/test_gradient_descent.jl")
        include("solvers/test_gradient_sampling.jl")
        include("solvers/test_interior_point_Newton.jl")
        include("solvers/test_Levenberg_Marquardt.jl")
        include("solvers/test_mesh_adaptive_direct_search.jl")
        include("solvers/test_Nelder_Mead.jl")
        include("solvers/test_projected_gradient.jl")
        include("solvers/test_proximal_bundle_method.jl")
        include("solvers/test_proximal_gradient_method.jl")
        include("solvers/test_proximal_point.jl")
        include("solvers/test_quasi_Newton.jl")
        include("solvers/test_quasi_Newton_box.jl")
        include("solvers/test_particle_swarm.jl")
        include("solvers/test_primal_dual_semismooth_Newton.jl")
        include("solvers/test_stochastic_gradient_descent.jl")
        include("solvers/test_subgradient_method.jl")
        include("solvers/test_truncated_cg.jl")
        include("solvers/test_trust_regions.jl")
        include("solvers/test_vectorbundle_newton.jl")
    end
    include("test_aqua.jl")
    include("test_deprecated.jl")
end
