ignore:
  - "src/helpers/exports/.*" # exclude exports, since there are no CI tests for Asy-exports
  - "src/documentation_glossary.jl" # exclude this since it is just use to create the docs and code cov goes bogus on this.
  - "src/helpers/test.jl" # exclude tests since they are not part of the package code but merely helpers