
project:
  title: "Manopt.jl"
  #execute-dir: project

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
bibliography:
  - CITATION.bib
  - bib/bibliography.bib
csl: nature.csl
fig-format: png

execute:
  freeze: auto
  eval: true
  echo: true
  output: true

jupyter: julia-1.8
