[default.extend-words]
methodes = "methodes" # french
Serie = "Serie" # french
sur = "sur" # french
cmo = "cmo" # often used abbreviation for constrained manifold objective
BA = "BA" # Maybe rename that shortened version in the tests
nd = "nd" # like in 2nd

[files]
extend-exclude = [
"tutorials/*.html",
# rendered from tutorials/*.qmd, so we do not want to check for typos twice
"docs/src/tutorials/*.md",
"joss/paper.md",
]
