
Base.@deprecate_binding ManifoldGradientObjective ManifoldFirstOrderObjective
Base.@deprecate_binding AbstractManifoldGradientObjective AbstractManifoldFirstOrderObjective
Base.@deprecate_binding ManifoldCostGradientObjective ManifoldCombinedFirstOrderObjective
