Base.@deprecate_binding HeestenesStiefelCoefficient HestenesStiefelCoefficient
export HeestenesStiefelCoefficient
Base.@deprecate_binding SimpleCacheObjective SimpleManifoldCachedObjective
export SimpleCacheObjective
