name: Documenter
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.353
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.9
      - name: Cache Quarto
        id: cache-quarto
        uses: actions/cache@v3
        with:
          path: tutorials/_freeze
          key: ${{ runner.os }}-quarto-freeze--${{ hashFiles('tutorials/_freeze/**') }}
      - name: Cache Documenter
        id: cache-documenter
        uses: actions/cache@v3
        with:
          path: docs/src/tutorials
          key: ${{ runner.os }}-documenter-tutorials-${{ hashFiles('docs/src/tutorials/**') }}
      - name: Cache CondaPkg
        id: cache-condaPkg
        uses: actions/cache@v3
        with:
          path: docs/.CondaPkg
          key: ${{ runner.os }}-condapkg-${{ hashFiles('docs/.CondaPkg/**') }}
      - name: "Documenter rendering (including Quarto)"
        run: "docs/make.jl --quarto"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
