name: Documenter
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # To resolve to render this: How to install all dependencies like Python, Jupyter, julia, IJulia,...
      #- uses: quarto-dev/quarto-actions/render@v2
      #  with:
      #    path: tutorials
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.8
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
