name: Documenter
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.353
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.9
      - name: Install Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.11'
      - name: Install Jupyter
        run: pip install jupyter
      - name: Cache Quarto
        id: cache-quarto
        uses: actions/cache@v3
        with:
          path: _frreeze
          key: ${{ runner.os }}-quarto-freeze
      - name: Cache Documenter
        id: cache-documenter
        uses: actions/cache@v3
        with:
          path: docs/src/tutorials
          key: ${{ runner.os }}-documenter-tutorials
      - name: Render Tutorials
        run: "quarto render tutorials/*.qmd"
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
